const loader = `<div class="d-flex align-items-center loader-container">
    <div class="loadingio-spinner-bean-eater-s012rtor8r"><div class="ldio-z5309jiu3qm">
    <div><div></div><div></div><div></div></div><div><div></div><div></div><div></div></div>
</div></div></div>

<style type="text/css">
    @keyframes ldio-z5309jiu3qm-1 {
        0% { transform: rotate(0deg) }
        50% { transform: rotate(-45deg) }
        100% { transform: rotate(0deg) }
    }
    @keyframes ldio-z5309jiu3qm-2 {
        0% { transform: rotate(180deg) }
        50% { transform: rotate(225deg) }
        100% { transform: rotate(180deg) }
    }
    .ldio-z5309jiu3qm > div:nth-child(2) {
        transform: translate(-15px,0);
    }
    .ldio-z5309jiu3qm > div:nth-child(2) div {
        position: absolute;
        top: 40.599999999999994px;
        left: 40.599999999999994px;
        width: 121.79999999999998px;
        height: 60.89999999999999px;
        border-radius: 121.79999999999998px 121.79999999999998px 0 0;
        background: #1c4595;
        animation: ldio-z5309jiu3qm-1 0.9900990099009901s linear infinite;
        transform-origin: 60.89999999999999px 60.89999999999999px
    }
    .ldio-z5309jiu3qm > div:nth-child(2) div:nth-child(2) {
        animation: ldio-z5309jiu3qm-2 0.9900990099009901s linear infinite
    }
    .ldio-z5309jiu3qm > div:nth-child(2) div:nth-child(3) {
        transform: rotate(-90deg);
        animation: none;
    }@keyframes ldio-z5309jiu3qm-3 {
         0% { transform: translate(192.85px,0); opacity: 0 }
         20% { opacity: 1 }
         100% { transform: translate(71.05px,0); opacity: 1 }
     }
    .ldio-z5309jiu3qm > div:nth-child(1) {
        display: block;
    }
    .ldio-z5309jiu3qm > div:nth-child(1) div {
        position: absolute;
        top: 93.38px;
        left: -8.12px;
        width: 16.24px;
        height: 16.24px;
        border-radius: 50%;
        background: #e76a24;
        animation: ldio-z5309jiu3qm-3 0.9900990099009901s linear infinite
    }
    .ldio-z5309jiu3qm > div:nth-child(1) div:nth-child(1) { animation-delay: -0.6767000000000001s }
    .ldio-z5309jiu3qm > div:nth-child(1) div:nth-child(2) { animation-delay: -0.33330000000000004s }
    .ldio-z5309jiu3qm > div:nth-child(1) div:nth-child(3) { animation-delay: 0s }
    .loadingio-spinner-bean-eater-s012rtor8r {
        width: 203px;
        height: 203px;
        margin: auto;
        display: inline-block;
        overflow: hidden;

    }
    .ldio-z5309jiu3qm {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
    }
    .ldio-z5309jiu3qm div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
</style>`

export default loader
